name: Custome Analytics Code Deployment 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: pip install wheel setuptools

    - name:  create wheel file 
      run: python setup.py bdist_wheel

    - name: copy wheel file 
      run: aws s3 cp dist/customer_analytics-0.1.0-py3-none-any.whl s3://mybucket31101999/code/customer_analytics/

    - name: copy glue start script 
      run: aws s3 cp glue_upload_script s3://mybucket31101999/code/customer_analytics/ --recursive
